### ISSUE TITLE
Pretrained Models of CelebA-HQ

### ISSUE THREAD

**Issue by jessemelpolio** [akanazawa/vgan#3]
Hi @akanazawa , it would be great if you could release the pretrained models of CelebA-HQ or other models in your paper. Do you have any plans to release the models?

**Comment by xbpeng** [comment]
Here's a pre-trained model for CelebA-HQ:
https://drive.google.com/file/d/1qwmQtkGm-i0IKFqSEVWugh4DVpJW4CQJ/view?usp=sharing
You can run it with test.py.

**Comment by jessemelpolio** [comment]
Great thanks.
