### ISSUE TITLE
gan loss and gradient penalty

### ISSUE THREAD

**Issue by lumosity4tpj** [akanazawa/vgan#5]
hi, @akanazawa How to explain the combination of standard gan and gradient penalty when you run the experiments on the celeba dataset.

**Comment by akanazawa** [comment]
Hi,  if I understand your question correctly, I think this would be referred to as simply GP?

**Comment by lumosity4tpj** [comment]
OK, thanks for your reply. I am just confused about choosing the standard gan & gp over the wgan-gp.
